### PR TITLE
Design/Architecture tweaks

### PR DESCRIPTION
**Pull request by ttilley**
I've modified the design of the processor class hierarchy with the goal of making it as effortless to extend and maintain as possible. The two primary changes here are that processor lookup is done via a registry class and key processing is determined by naming convention rather than an if/else block. Macros have been added to reduce repetitive boilerplate.

A good example of how this makes processor classes clean and easy to maintain:

``` objc
@implementation UIViewControllerProcessor

RegisterOnLoadWithIB

BooleanKey(definesPresentationContext)
BooleanKey(hidesBottomBarWhenPushed)
BooleanKey(wantsFullScreenLayout)
BooleanKey(providesPresentationContextTransitionStyle)
KeyValueMethod(modalPresentationStyle, uiModalPresentationStyleString)
KeyValueMethod(modalTransitionStyle, uiModalTransitionStyleString)

@end
```

I'm lazy, so I've only updated the direct subclasses with the new style. Overwriting processKey:value: works the same as always provided a fallback call to super is made, which all processors other than direct subclasses already do.

Thoughts?

### CODE REVIEW

**Comment by akosma** [comment]
WHOA

Well first of all I want you to know that I'm impressed by your work! I have to take some time to see how your approach works. I'll checkout your branch and play with it, and see how it goes. But what I've seen so far is IMPRESSIVE.

Again, thanks! I'll be back with comments. Promise.

Adrian

**Comment by ttilley** [comment]
Thankyou kindly. :)

**Comment by ttilley** [comment]
Any opinions? Anything you'd like to see changed before merge? Anything you'd like to see split up into smaller chunks?

**Comment by akosma** [comment]
Sorry for the delay.
Actually I'm not going to merge this pull request, as I have to admit that the idea looks good and you've done a great job, but I strongly dislike the use of macros for this.
Thanks again! Best,

**Pull request closed without merging**
